github: hipersayanX
patreon: hipersayanx
ko_fi: hipersayanx
liberapay: hipersayanx
custom: ["https://www.paypal.me/WebcamoidDonations", "https://buymeacoffee.com/hipersayanx", "https://webcamoid.github.io/donations#crypto"]
